regex_map = [
    ["^b.*d.*c.*s.*", "bkwd-dash ch. shot"],
    ["^b.*d.*c.*f.*", "bkwd-dash cont. fire"],
    ["^b.*r.*n.*", "burning"],
    ["^c.*n.*f.*s.*n", "confusion"],
    ["^d.*c.*s.*", "dash ch. shot"],
    ["^d.*c.*f.*", "dash cont. fire"],
    ["^effect duration|^ed$", "effect duration"],
    ["^e.*v.*", "evasion"],
    ["^f.*r.*z.*", "freezing"],
    ["^f.*h.*b.*", "full-health boost"],
    ["^f.*d.*c.*f.*", "fwd-dash cont. fire"],
    ["health", "health"],
    ["^heart bonus|^hb$", "heart bonus"],
    ["^i.*p.*a.*b.*", "in-peril attack boost"],
    ["^i.*p.*a.*d.*", "in-peril autododge"],
    ["^it.*m a.t.*k", "item attack"],
    ["^k.*kb.*k d*f.*n.*s.*|^kd$", "knockback defense"],
    ["^k.*kb.*k r.*|^kr$", "knockback recovery"],
    ["^melee combo|^mc$", "melee combo"],
    ["^m.*d.*a.*", "melee dash attack"],
    ["^m.*d.*", "melee defense"],
    ["^o.*d.*", "overall defense"],
    ["^para.*", "paralysis"],
    ["^petri.*", "petrification"],
    ["^p.*s.*n$", "poison"],
    ["^power attack|^pa$", "power attack"],
    ["^recovery effect|^re$", "recovery effect"],
    ["^r.*n.*g.*s.*p.*d$|^rs$", "running speed"],
    ["^sh.t h.*m.*g$|^sh$", "shot homing"],
    ["^s.lf.*in.*j.*y$|^si$", "self injury"],
    ["^s.*k.*n.*g$", "shaking"],
    ["^s.*t.*c.*l.*t.*n$|^sc$", "shot cancellation"],
    ["^s.*t.*d.*f.*n.*e$|^sd$", "shot defense"],
    ["^s.*t.*r.*n.*e|^sr$", "shot range"],
    ["^s.*d.*c.*s.*", "side-dash ch. shot"],
    ["^s.*d.*c.*f.*", "side-dash cont. fire"],
    ["^s.*p.*d.*", "speed"],
    ["^s.*t.*m.*n.*a", "stamina"],
    ["^s.*c.*f.*", "standing cont. fire"],
    ["^s.*c.*s.*", "standing ch. shot"],
    ["^st.*res.*", "status resistance"],
    ["^w.*s.*", "walking speed"],
    ["^w.*k.*n.*", "weakening"]
]
